---
- name: Install icecast package
  apt:
    name: icecast2
    state: present
    update_cache: yes

- name: Enable icecast (disabled system wide by default)
  template:
    src: icecast2.j2
    dest: /etc/default/icecast2

- name: Generate icecast.xml file
  template:
    src: icecast.xml.j2
    dest: "{{ icecast_configfile }}"
  notify: restart icecast

- name: Enable icecast service
  service:
    name: icecast2
    enabled: yes